### ISSUE TITLE
Support for EC2 Dedicated Hosts

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#4034]
## Purpose

EC2 Dedicated Hosts are now available for general use across a wide variety of AWS regions, so we should look at supporting them in Terraform.

This is intended as an umbrella issue to discuss changes we may wish to make with respect to new and existing resources in order to support dedicated hosts in an effective manner.
## Resources
- [Blog post announcing availability](https://aws.amazon.com/blogs/aws/now-available-ec2-dedicated-hosts/)
- [Feature page](http://aws.amazon.com/ec2/dedicated-hosts/)
- [Pricing](http://aws.amazon.com/ec2/dedicated-hosts/pricing/)
- [`AllocateHosts` API](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AllocateHosts.html)
- [`Placement` data type which allows instances to be launched onto a dedicated host using the `RunInstances` API call](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Placement.html)
## Tasks
- [ ] Verify Go SDK support for the AllocateHost operation etc
- [ ] Add `aws_dedicated_host` resource to Terraform
- [ ] Determine whether we want to add options for launching on to a dedicated host to `aws_instance` or whether we want a new resource type along the lines of `aws_dedicated_host_instance`.
- [ ] Add acceptance tests
- [ ] Add documentation

**Comment by SPhu** [comment]
+1

**Comment by stack72** [comment]
Hi @jen20 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

**Comment by calvin-hartwell** [comment]
Sorry to bump, has this been added/fixed now or was the feature rejected?

**Comment by dheepansn** [comment]
We should need this feature added in Terraform as many of organization started using dedicated host to better performance and To utilize their own BYOL.

**Comment by paultyng** [comment]
This feature request is tracked on the AWS provider repo: https://github.com/terraform-providers/terraform-provider-aws/issues/10752
