### ISSUE TITLE
provider/aws: All open OpsWorks issues, with PRs, targeted for inclusion in v0.6.15?

### ISSUE THREAD

**Issue by u2mejc** [hashicorp/terraform#6245]
This is a consolidation of every [known] OpsWorks issue broken v0.6.14, each with a PR, with the hope that we can get OpsWorks stable in 0.6.15! 🚀  Also if anyone sees a PR / Issue I missed, please let me know.
- [x] provider/aws: OpsWorks stack creation brocken - **Released in 0.6.15**
  - This is a bad one, a [PR merged](https://github.com/hashicorp/terraform/issues/5724) caused a regression that broke OpsWorks for almost every OS except 12.04. 💥 
  - Related: #5569 #5905 #5958 #6221 
  - **PR to fix:** https://github.com/hashicorp/terraform/pull/6244
- [x] Roll up issue for known ignore_changes problems - #5627 
  - Worth mentioning as is comes up in issues `is:issue is:open opsworks`, ignore_changes works well in my testing. ie:

```
    lifecycle {
        ignore_changes = ["custom_cookbooks_source.0.ssh_key"]
    }
```
- [ ] AWS Opsworks Rails App Layer ignores manage_bundler #5907
  - **PR to fix:** _no PRs submitted yet_
- [x] providers/aws: add aws_s3_bucket resource region argument #6051 
  - Not directly a OpsWorks issue, but related because S3 bucket creation outside us-east-1 is broken when using OpsWork resources in the same modules path.
  - **PR to fix:** ~~6243~~ _No pending PRs_
- [x] provider/aws : Opsworks fails on update #6077  - **Released in 0.6.15**
  - This issues assumes that every stack will us custom cookbooks. With the growth and quality of the supermarket, this isn't true anymore and the bug breaks updates for stacks not using custom cookbooks.
  - **PR to fix:** #6078  (checked off by @catsby)
- [x] provider/aws: TestAccAWSOpsworksCustomLayer tests failing inconsistently #6201
  - I also wasn't able to reproduce this issue, something uniqe with Paul's env. A wild guess on my part would be a deleted default VPC issue?

**Comment by janschumann** [comment]
@u2mejc As mentioned in #4419, some attributes of an `aws_opsworks_application` resource are not passed to the underlying go idk for some reason. 

E.g. the attribute `document_root` is always empty. That is when creating that resource and also when refreshing the state after editing that resource manually.

Can you confirm, that you can not reproduce this behavior? Otherwise I would create an issue.

**Comment by u2mejc** [comment]
Thank you @catsby!

@janschumann I wasn't able to reproduce it previously, I believe it's because I'm using custom layers only. I poked at the ruby issue briefly and it's a weird one. It actually sends the boolean mentioned in #5907 as a `1` instead of a `true`. Then when `plan` is ran again, it fails to compare that `false` doesn't match what is in the resource.

I'll poke at it tomorrow, but if you or anyone else has a lead on the issue, please shoot up a PR, I don't presently have one staged for that issue.

**Comment by u2mejc** [comment]
**UPDATE:** v0.6.15 has been released, and Opsworks support has been radically improved. Instance and stack creation are not supported, a nasty regression in creating stacks has been resolved, failing to update stacks was resolved, and plenty of other small feature / issues.

Still the biggest outstanding issue now is language or app specific layers are not being transmitted properly to AWS and silently fail to be properly diff'ed on subsequent runs. #5907

I'm also going to close the s3 issue PR. I'm not feeling good traction on wrapping my head around the issue, and I want to make sure that anyone who wants to work on the issue isn't turned away by seeing my open WIP.

**Comment by ericgoedtel** [comment]
@janschumann Were you able to find a fix to the problem regarding `document_root`? I am seeing a similar if not identical problem. `terraform` is not setting or fetching the value of document root and saving it to tfstate.

**Comment by janschumann** [comment]
UPDATE: as off 0.7.13 the `document_root` problem still exists. I will work on this now.

**Comment by stack72** [comment]
What is the status of the rest of this ticket?

Paul

**Comment by janschumann** [comment]
@stack72 sorry, just seen this right now. I will try to figure out the status and also look if there are any other opsworks related issues.

**Comment by janschumann** [comment]
- [ ] AWS  Opsworks Rails App Layer ignores manage_bundler #5907
  - PR to fix: #7219 (but reopened)
  - I will figure out, if I can work on that

All other issues, including all opsworks application issues regarding additional attributes (#10477) should be fixed.

**Comment by stack72** [comment]
the PR (#10669) from @janschumann shows that this can now be closed - thanks for all the work here @u2mejc and @janschumann :)
